### ISSUE TITLE
[feat] Convert from OSM data (files or links)

### ISSUE THREAD

**Issue by lgrd** [IGNF/route-graph-generator#47]
### Need 

r2gg can create a .osm from the pivot. And r2gg can read them to create osrm or valhalla data. But it can't convert an osm data to pivot. 

### Functionalities 

- Download an osm file 
- Convert an osm file to the pivot format
- Be able to make an entire generation from osm to pgr, osrm and valhalla

### Tasks 

- [ ] Update the generation file format 
- [ ] Be sure of the CLI and its IO
- [ ] Code it 
- [ ] Update and run tests
- [ ] Update docs (changelog and documentation directory)

### Code 

// TODO
